language: node_js
node_js:
  - "8"
jobs:
  - before_script:
      - export PATH="$HOME/.yarn/bin:$PATH"
      - yarn global install docma
    script:
      - yarn
      - yarn test
  - stage: deploy
    script: docma -c docma.json
    deploy:
      provider: npm
      email: "hayden@haydenbjyoung.me"
      api_key: ""
      on:
        tags: true